version: '3'
services:
  prod:
    container_name: nextjs-prod
    build:
      target: production
      context: .
      dockerfile: Dockerfile
      # network: host
    # restart: always
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
      - /opt/app/.next
    ports:
      - '8000:8000'